Repository googleapis/java-datalabeling, pull requests merged in 2020-09, with the labels that each got.

#240 chore: regenerate README
  README.md
  synth.metadata
Labels: api: datalabeling, cla: yes, context: none

#242 chore: regenerate templates
  .github/CODEOWNERS
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#256 build(java): use yoshi-approver token for auto-approve
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#255 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: datalabeling, automerge, cla: yes

#262 chore: regenerate templates
  .github/readme/synth.py
  .github/workflows/auto-release.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#264 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
