Repository googleapis/java-datalabeling, pull requests merged in 2020-10, with the labels that each got.

#267 build(java): readme.sh should be executable
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#281 ci(java): restrict presubmit samples ITs to only snapshot
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#282 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#286 build(java): auto-approve README regeneration
  .github/workflows/approve-readme.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#289 build(java): enable snippet-bot
  .github/snippet-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full

#293 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#294 chore: clean up and update renovate.json
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#296 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#299 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#302 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#300 chore: regenerate common templates
  .kokoro/release/publish_javadoc.sh
  CODE_OF_CONDUCT.md
  synth.metadata
Labels: api: datalabeling, automerge, cla: yes, context: full

#304 chore(ci): fix typo in restrict presubmit samples ITs to only snapshot
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#306 chore(java): enable generated-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full

#285 fix(build): checkstyle violations
  samples/snippets/src/main/java/com/example/datalabeling/CreateAnnotationSpecSet.java
  samples/snippets/src/main/java/com/example/datalabeling/CreateDataset.java
  samples/snippets/src/main/java/com/example/datalabeling/CreateInstruction.java
  samples/snippets/src/main/java/com/example/datalabeling/ExportData.java
  samples/snippets/src/main/java/com/example/datalabeling/ImportData.java
  samples/snippets/src/main/java/com/example/datalabeling/LabelImage.java
  samples/snippets/src/main/java/com/example/datalabeling/LabelText.java
  samples/snippets/src/main/java/com/example/datalabeling/LabelVideo.java
  samples/snippets/src/test/java/com/example/datalabeling/CreateAnnotationSpecSetIT.java
  samples/snippets/src/test/java/com/example/datalabeling/CreateDatasetIT.java
  samples/snippets/src/test/java/com/example/datalabeling/CreateInstructionIT.java
  samples/snippets/src/test/java/com/example/datalabeling/ImportDataIT.java
  samples/snippets/src/test/java/com/example/datalabeling/LabelImageIT.java
Labels: api: datalabeling, cla: yes

#307 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes
