Repository googleapis/java-datalabeling, pull requests merged in 2020-08, with the labels that each got.

#222 samples: migrate samples from GoogleCloudPlatform/java-docs-samples /datalabeling/beta/cloud-client
  samples/snippets/src/main/java/com/example/datalabeling/CreateAnnotationSpecSet.java
  samples/snippets/src/main/java/com/example/datalabeling/CreateDataset.java
  samples/snippets/src/main/java/com/example/datalabeling/CreateInstruction.java
  samples/snippets/src/main/java/com/example/datalabeling/ExportData.java
  samples/snippets/src/main/java/com/example/datalabeling/ImportData.java
  samples/snippets/src/main/java/com/example/datalabeling/LabelImage.java
  samples/snippets/src/main/java/com/example/datalabeling/LabelText.java
  samples/snippets/src/main/java/com/example/datalabeling/LabelVideo.java
  samples/snippets/src/test/java/com/example/datalabeling/CreateAnnotationSpecSetIT.java
  samples/snippets/src/test/java/com/example/datalabeling/CreateDatasetIT.java
  samples/snippets/src/test/java/com/example/datalabeling/CreateInstructionIT.java
  samples/snippets/src/test/java/com/example/datalabeling/ImportDataIT.java
  samples/snippets/src/test/java/com/example/datalabeling/LabelImageIT.java
  samples/snippets/src/test/java/com/example/datalabeling/LabelTextIT.java
  samples/snippets/src/test/java/com/example/datalabeling/LabelVideoIT.java
Labels: cla: yes

#223 chore: regenerate README list
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#229 samples: add presubmit lint check
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#234 build: temporarily disable reporting to unblock releases
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: datalabeling, cla: yes, context: full

#235 build(java): switch to release-publish app for notifying GitHub of release status
  .kokoro/release/stage.cfg
  .kokoro/release/stage.sh
  synth.metadata
Labels: cla: yes, context: full
