Repository googleapis/java-datalabeling, pull requests merged in 2020-06, with the labels that each got.

#180 chore(java_templates): add default CODEOWNERS files for samples reviews
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#182 chore: turn on renovate-bot master issue for java repos
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#184 build(java): skip lint on samples directory
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#186 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#190 chore: update README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#194 ci: switch to secret manager for sample/integration tests
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#197 feat(deps): adopt flatten plugin and google-cloud-shared-dependencies
  .gitignore
  google-cloud-datalabeling/pom.xml
  grpc-google-cloud-datalabeling-v1beta1/pom.xml
  pom.xml
  proto-google-cloud-datalabeling-v1beta1/pom.xml
Labels: cla: yes

#201 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#207 fix: migrate to grpc_service_config
  README.md
  google-cloud-datalabeling/src/main/java/com/google/cloud/datalabeling/v1beta1/DataLabelingServiceClient.java
  google-cloud-datalabeling/src/main/java/com/google/cloud/datalabeling/v1beta1/DataLabelingServiceSettings.java
  google-cloud-datalabeling/src/main/java/com/google/cloud/datalabeling/v1beta1/package-info.java
  google-cloud-datalabeling/src/main/java/com/google/cloud/datalabeling/v1beta1/stub/DataLabelingServiceStub.java
  google-cloud-datalabeling/src/main/java/com/google/cloud/datalabeling/v1beta1/stub/DataLabelingServiceStubSettings.java
  google-cloud-datalabeling/src/main/java/com/google/cloud/datalabeling/v1beta1/stub/GrpcDataLabelingServiceStub.java
  google-cloud-datalabeling/src/test/java/com/google/cloud/datalabeling/v1beta1/DataLabelingServiceClientTest.java
  synth.metadata
Labels: automerge, cla: yes, context: partial

#210 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none
