Repository googleapis/java-datalabeling, pull requests merged in 2021-05, with the labels that each got.

#471 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: datalabeling, automerge, cla: yes, context: none

#472 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: datalabeling, automerge, cla: yes

#473 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: datalabeling, automerge, cla: yes, context: full

#478 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: datalabeling, automerge, cla: yes

#479 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: datalabeling, automerge, cla: yes

#480 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: datalabeling, automerge, cla: yes, context: full

#485 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: datalabeling, automerge, cla: yes

#486 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: datalabeling, automerge, cla: yes, context: full

#488 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: datalabeling, automerge, cla: yes, context: full

#491 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: datalabeling, automerge, cla: yes, context: full

#495 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: datalabeling, automerge, cla: yes

#496 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: datalabeling, automerge, cla: yes

#497 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: datalabeling, automerge, cla: yes
